--- 
author: "Ishtyaq Habib"
author_image: /assets/images/author.jpg
baseurl: ""
cover: /assets/images/StarTrailsOpt.png
description: "Designer - Developer - Scientist\n"
email: ishtyaq.habib@gmail.com
gems: 
  - jemoji
  - jekyll-paginate
loat_logo: true
logo: /assets/images/logo.png
name: "Ishtyaq Habib"
paginate: 5
social: 
  - 
    desc: "Fork me on github"
    icon: github
    share_link: ~
    share_title: ~
    share_url: ~
    url: "https://github.com/tyaq"
  - 
    desc: "Follow me on codepen"
    icon: codepen
    share_link: ~
    share_title: ~
    share_url: ~
    url: "http://codepen.io/tyaq/"
  - 
    desc: "Follow me on twitter"
    icon: twitter
    share_link: "&url="
    share_title: "?text="
    share_url: "http://twitter.com/share"
    url: "https://twitter.com/t_yaq"
title: "Ishtyaq Habib"
twitter_handle: "@t_yaq"
url: "http://ishtyaqhabib.com"
theme: jekyll-theme-minimal